# Generated by Django 3.0.5 on 2020-08-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='artist_photo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fb',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='insta',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='abc@xyz.com', max_length=254),
        ),
    ]
